### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by caressgents** [5ymph0en1x/SyBrain#1]
`Traceback (most recent call last):
  File "sybrain.py", line 6, in <module>
    from utils import bitmex_http_conn2 as bitmex
ImportError: cannot import name 'bitmex_http_conn2' from 'utils' (unknown location)`

Error received after getting all libs and modules installed then running python3 sybrain.py 

Any suggestions? @5ymph0en1x

**Comment by 5ymph0en1x** [comment]
Hello caressgents !

It's a mistake from my part, sorry about that...
This should be fixed now :-)

Best regards

**Comment by caressgents** [comment]
Cool, after getpull, now getting websocket errors - Could this be related to me trying to test on the Main net and not the test net of bitmex? If so, I don't see variables or source to switch out of testnet and to live net aside from test in the sybrain .py file. @5ymph0en1x 


`/SyBrain$ python3 sybrain.py
error from callback <bound method BitMEXWebsocket.__on_error of <utils.bitmex_websocket_com.BitMEXWebsocket object at 0x7f204f8360b8>>: __on_error() takes 2 positional arguments but 3 were given
error from callback <bound method BitMEXWebsocket.__on_close of <utils.bitmex_websocket_com.BitMEXWebsocket object at 0x7f204f8360b8>>: __on_close() takes 1 positional argument but 2 were given
/SyBrain$ python3 sybrain.py
error from callback <bound method BitMEXWebsocket.on_error of <utils.bitmex_websocket_com.BitMEXWebsocket object at 0x7f204f8360b8>>: __on_error() takes 2 positional arguments but 3 were given
error from callback <bound method BitMEXWebsocket.__on_close of <utils.bitmex_websocket_com.BitMEXWebsocket object at 0x7f204f8360b8>>: __on_close() takes 1 positional argument but 2 were given
^CTraceback (most recent call last):
  File "sybrain.py", line 29, in <module>
    api_key=API_key_bmex_test, api_secret=API_secret_bmex_test)
  File "/home/toor/SyBrain/utils/bitmex_websocket_com.py", line 49, in __init
    self.__connect(wsURL, symbol)
  File "/home/toor/SyBrain/utils/bitmex_websocket_com.py", line 140, in __connect
    sleep(1)
KeyboardInterrupt

**Comment by 5ymph0en1x** [comment]
@caressgents 
I think you just have to install websocket-client via pip3 to be ok.

**Comment by caressgents** [comment]
I've got websocket-client installed on version 0.46.0 (that's what my other algo calls for) do you think it would be because of the version? I've noticed a lot of algos calling for 0.56.0

**Comment by 5ymph0en1x** [comment]
It works with version 0.56.0.

Maybe you need to create a virtual environment for this project only and use the newly created requirements.txt I pushed earlier :-)

**Comment by caressgents** [comment]
@5ymph0en1x All done on new env, on websocket 0.56.0, using your requirements.txt, but now getting "ModuleNotFoundError: No module named 'numpy'" 

I have installed NumPy, and still receiving error. See following: 
`python3 sybrain.py
Traceback (most recent call last):
  File "sybrain.py", line 3, in <module>
    from stocks import Main  # Machine Learning Module
  File "/home/toor/sybran/SyBrain/stocks.py", line 8, in <module>
    from stockpredictor import StockPredictor, ParseData, PlotData
  File "/home/toor/sybran/SyBrain/stockpredictor.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'`

**Comment by 5ymph0en1x** [comment]
Chances are you are missing a dependency

`sudo apt-get install libatlas-base-dev`

Give that a shot and then run it again.

**Comment by caressgents** [comment]
@5ymph0en1x even with libatlas installed, still getting same error as above 'no module named 'numpy''

**Comment by caressgents** [comment]
@5ymph0en1x scratch that, got all the dependencies installed, now only getting 401 error on handshake, working to sort it, but any tips would be helpful

**Comment by caressgents** [comment]
@5ymph0en1x sorry, i think i found my issue, I've been trying to connect to main net, not testnet. I dug through the source, but cannot find where to disable testnet, and run on main net. 

Any advice?

**Comment by 5ymph0en1x** [comment]
When you clone this repo and don't touch anything (except changing key and secret details), the algo will try to connect to the main net by default.

The only way to make it run on the test net is to change line 11 value to "wss://testnet.bitmex.com/realtime" and line 31, "test=True".

**Comment by caressgents** [comment]
Got it running. Ended up removing original clones in the new env, and booted right up. 

However, it went through the learning modes, and then produced the following error when placing an order: 

`Machine learning : DOWN !
Average Fair Price Variation: -0.005420000000000072 - Last Variation: -0.015300000000006548 - Last Fair Price: 9931.5 - Position Taken: 0 - Balance: 16268054
Checking OrderBook...
Sell Side: 4796784 - Buy Side: 156511
Go Sell !
Balance before: 16268054
SELL @ 9934.5
Balance - Step 1 of 2: 16268054
0 is not of type 'string'

Failed validating 'type' in schema:
    {'description': 'Order ID',
     'in': 'formData',
     'name': 'orderID',
     'required': False,
     'type': 'string'}

On instance:
    0
 This is the end !
Traceback (most recent call last):
  File "sybrain.py", line 367, in <module>
    bmex()
  File "sybrain.py", line 276, in bmex
    while ws_bmex.ws.sock.connected:
AttributeError: 'NoneType' object has no attribute 'connected'`


@5ymph0en1x

**Comment by 5ymph0en1x** [comment]
Good to see some progress !
Try restarting the algo right after it crashes. I noticed that the websocket link seems to be weak when first connect.

**Comment by caressgents** [comment]
Restarting seemed to work. 

Have been running for a bit now. Interesting strategy.

**Comment by 5ymph0en1x** [comment]
Great news !

I'm currently working on a spin-off strategy that will only trade by scanning the orderbook.

Stay tuned...

By the way, feel free to tip to allow further developments :-)

BTC: 3BMEXbS4Neu5KwsiATuZVowmwYD3UPMuxo

Best regards

**Comment by caressgents** [comment]
For sure - 

One more question, how in this script, can I force limit orders only?

**Comment by 5ymph0en1x** [comment]
Interesting question !
I see someone has been studying fees structure :-D
That's what my new strategy will be about : maximizing profit by using maker fees.
Right now, SyBrain doesn't allow limit orders use easily.
